<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJdwzHxv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJdwzHxv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJdwzHxv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJdwzHxv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJdwzHxv\App_KernelDevDebugContainer([
    'container.build_hash' => 'JdwzHxv',
    'container.build_id' => '51936500',
    'container.build_time' => 1644935988,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJdwzHxv');
